name: hotkey_manager
description: This plugin allows Flutter desktop apps to defines system/inapp wide hotkey (i.e. shortcut).
version: 0.1.9
homepage: https://github.com/leanflutter/hotkey_manager

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter

  collection: ^1.15.0
  uuid: ^3.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      linux:
        pluginClass: HotkeyManagerPlugin
      macos:
        pluginClass: HotkeyManagerPlugin
      windows:
        pluginClass: HotkeyManagerPlugin
